FROM ubuntu:xenial
MAINTAINER Yapeng-Shi yapengshi66@gmail.com

RUN apt-get update -q && apt-get install -qy \
    curl jq \
    texlive-full \
    python-pygments gnuplot \
    make git \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /data
VOLUME ["/data"]
